sweety/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'welcome/index' => 'welcome#index'

  resources :users

  resources :sessions, :only => [:new, :create]
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :readings

  resources :reports, :only => [:new, :create]

end

sweety/app/models/reading.rb
class Reading < ActiveRecord::Base
	belongs_to :user
	before_save :set_date
	validates :level, presence: true, numericality: { only_integer: true }
	validate :user_quota, :on => :create

  def set_date
    self.date = Date.today
  end

	def self.created_today(date)
		where(date: date)
	end

	def self.month_to_date(date)
		date = Date.strptime(date, '%Y-%m-%d')
		where(date: (date.beginning_of_month..date))
	end

	def self.in_past_month(date)
		date = Date.strptime(date, '%Y-%m-%d')
		where(date: ((date - 30.days)..date))
	end

	private

	def user_quota
   errors.add(:user_quota, "Exceeds daily limit") if user.readings.today.count >= 4
  end
end

sweety/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, uniqueness: true, presence: true

  has_many :readings do
	  def today
	      where(:created_at => (Time.zone.now.beginning_of_day..Time.zone.now))
	  end
	end
end

sweety/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
    if (@user == nil) then
      @user = User.new
    end
    return @user
  end

  def auth_user
    redirect_to '/sessions/new' unless session[:user_id]
  end
end

sweety/app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
	before_action :auth_user
	before_action :current_user

	def index
		redirect_to '/users/new' unless session[:user_id]
	end

	def new
		@reading = Reading.new
	end

	def create
		@reading = Reading.new(level: params[:reading][:level], user_id: current_user.id)
		if @reading.save
			redirect_to root_path, success: "Logged in successfully"
		else
			render 'new'
		end
	end

	def destroy

	end

	private

	def reading_params
		params.require(:reading).permit(:level)
	end
end

sweety/app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	before_action :auth_user
	before_action :current_user

	def new

	end

	def create
		readings = get_readings_from_range(params[:time_range])
		@report = create_report(readings) if readings.length > 0
	end

  private

  def report_params
  	params.permit(date, time_range)
  end

  def get_readings_from_range(range)
  	if range == '1'
  		current_user.readings.created_today(params[:date]['end_date'])
  	elsif range == '2'
  		current_user.readings.month_to_date(params[:date]['end_date'])
  	else
  		current_user.readings.in_past_month(params[:date]['end_date'])
  	end
  end

  def create_report(readings)
		levels = readings.map {|reading| reading.level}
		data_set = {}
		data_set[:max] = levels.max
		data_set[:min] = levels.min
		data_set[:average] = get_average(levels)
		data_set
	end

	def get_average(readings)
		readings.inject{ |sum, number| sum + number } / readings.size
	end
end

sweety/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	before_action :current_user, except: [:destroy]

  def new

	end

	def create
		user = User.find_by(name: params[:session][:name])
    if (user && user.authenticate(params['session']['password']))
      session[:user_id] = user.id
      redirect_to root_path, success: "Logged in successfully"
    else
      flash.now[:alert] = "Invalid login/password combination"
      render :action => 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

sweety/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	current_user
  end

  def create
  	@user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to '/welcome/index'
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :password)
  end
end

sweety/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_action :auth_user, except: [:login]
	before_action :current_user

	def index

	end

	def login

	end
end

sweety/app/helpers/application_helper.rb
module ApplicationHelper
end

sweety/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sweety</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/header'%>
<div id="main-container" class="container">
<%= yield %>
</div>

</body>
</html>

sweety/app/views/readings/new.html.erb
<div class="row">
	<div class="errors">
		<% if @reading.errors.any? %>
		<div class="errors">
	    <p>Sorry, we couldn't save your reading because:</p>
	    <ul>
		    <% @reading.errors.full_messages.each do |msg| %>
		      <li><%= msg %></li>
		    <% end %>
	    </ul>
		</div>
		<% end %>
	</div>
	<div>
		<h1>Enter a reading</h1>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<%= form_for @reading, :html => {:class => "form-inline"} do |f| %>
			<div class="form-group">
				<%= f.label :level, 'My blood glucose level is' %>
				<%= f.text_field :level, class: "form-control" %>
				<span class="input-group-btn">
				  <%= f.submit "Enter", class: "btn btn-default" %>
		    </span>
			</div>
		<% end %>
	</div>
</div>

sweety/app/views/reports/create.html.erb
<% if @report %>
	<h1>Your blood glucose levels for this period were</h1>
	<p>Max: <%= @report[:max] %>, Min: <%= @report[:min] %>, Average: <%= @report[:average] %></p>
	<%= link_to 'Submit a different date', new_report_path, class: "btn btn-default" %>
	<%= link_to 'Return home', root_path, class: "btn btn-default" %>
<% else %>
	<p>There are no entries for this day</p>
	<%= link_to 'submit a different date', new_report_path, class: "btn btn-default" %>
<% end %>

sweety/app/views/reports/new.html.erb
<h1>What report would you like to see?</h1>
<%= form_tag('/reports', :method => 'post', :class => "form-inline") do %>
	<div class="form-group">
	<%= label_tag(:date, "Select a date") %>
	<%= date_field(:date, :end_date, {class: "form-control"}) %>
	</div>
	<div class="form-group">
	<%= label_tag(:time_range, "Select a time range for your readings") %>
	<%= select_tag(:time_range, options_for_select([['Daily', 1], ['Month to date', 2], ['Past month', 3]]), class: "form-control", id: "report-time-range")  %>
	<%= submit_tag 'Enter', class: "btn btn-default" %>
	</div>
<% end %>

sweety/app/views/shared/_flashes.html.erb
<% unless flash.empty? %>
  <div id="flash">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
          <%= value %>
      </div>
    <% end %>
  </div>
<% end %>

sweety/app/views/shared/_header.html.erb
<nav class="navbar navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Sweety', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if @user.name.present? %>
        <li role="presentation" class="dropdown">
          <a class="dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            <%= @user.name %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <li><%= link_to 'Sign out', signout_path %></li>
          </ul>
        </li>
        <% else %>
        <li class="active"><%= link_to 'Sign in', new_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

sweety/app/views/users/_form.html.erb
<%= form_for @user do |f| %>
<%= f.label :name, 'User name' %>
<%= f.text_field :name %>
<%= f.label :password, 'Password' %>
<%= f.text_field :password %>
<%= f.submit "Submit" %>
<% end %>

sweety/app/views/users/new.html.erb
<h1>Sign up here</h1>

<% if @user.errors.any? %>
    <p>Sorry, your account can't be saved because:</p>
    <ul>
	    <% @user.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
    </ul>
<% end %>

<%= render partial: 'form' %>

sweety/app/views/welcome/index.html.erb
<%= render partial: 'shared/flashes' %>
<div class="jumbotron">
  <div class="container">
    <h1>Welcome, Sweety!</h1>
    <p>Sweety is a application for recording blood glucose levels for diabetics.</p>
    <p>Record up to four readings a day.</p>
    <p>View daily, monthly, and month-to-date reports on your levels.</p>
  </div>
</div>

<div class="container">
  <div class="row action-links">
    <div class="col-md-6">
      <h2><%= link_to 'Record a reading', new_reading_path %></h2>
    </div>
    <div class="col-md-6">
      <h2><%= link_to 'View a report', new_report_path %></h2>
    </div>
  </div>